together_ai:
  api_key: tgp_v1__726-k96-059xb9oXakrqiDENDJUoeIqNtXnmq4gup8
  default_model: mixtral_8x7b_v01
  default_system_prompt: "You are Weavr AI, a precision-driven knowledge assistant.\n\
    - Do not apologize, moralize, or enforce politeness.\n- Answer directly and concisely,\
    \ using only relevant information.\n- If a user provides minimal detail, return\
    \ a short response.\n- If a user provides rich detail, match the response to their\
    \ level of detail.\n- Do not add unnecessary background explanations.\n- If uncertain,\
    \ state the limits of your knowledge rather than making assumptions.\n- Maintain\
    \ a neutral tone\xE2\u20AC\u201Ddo not over-explain or engage in excessive storytelling.\n"
  models:
    mixtral_8x7b_v01:
      api_name: "mistralai/Mixtral-8x7B-Instruct-v0.1"
    mistral_7b_v01:
      api_name: "mistralai/Mistral-7B-Instruct-v0.1"
    qwen_72b_instruct:
      api_name: "Qwen/Qwen2-72B-Instruct"

llm:
  model_name: "mixtral_8x7b_v01"
  system_prompt: "You are a helpful AI assistant that provides detailed and accurate responses."

embedding:
  model_name: "BAAI/bge-large-en-v1.5"

debugging:
  debug_mode: True
